/**
 * Bulk backfill / refresh of <SaveThisTone /> CTAs across blog posts.
 *
 * Two modes:
 *   --apply         add CTA to posts that don't have one
 *   --replace       overwrite existing freeform CTA blocks generated by
 *                   this script (detected by trailing
 *                   `<SaveThisTone\n  title="...` block at end of file)
 *
 * Recipe-linked CTAs (`<SaveThisTone recipeSlug="..." />`) and hand-curated
 * freeform CTAs from `apply-save-this-tone.ts` are preserved unless --force.
 *
 * Classification cascade for each post:
 *   1. Artist tag → first recipe by that artist (recipe-linked card)
 *   2. Platform tag (helix/katana/tonex/quad-cortex/fractal/kemper)
 *      → /browse?platform=...
 *   3. Tone-character tag (fuzz/clean/high-gain/...) → /browse?tag=...
 *   4. Genre tag → /browse?genre=...
 *   5. Fallback → /browse
 *
 * Copy is written to sound like one guitarist talking to another — no
 * marketing-speak, no count-flexing, concrete song/artist names where the
 * data supports it.
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { toneRecipes, songs, artists } from "../src/lib/data";

const BLOG_DIR = path.join(process.cwd(), "content", "blog");
const APPLY = process.argv.includes("--apply");
const REPLACE = process.argv.includes("--replace");
const FORCE = process.argv.includes("--force");

/**
 * Slugs of the 159 posts originally backfilled by this script (commit
 * cc5cdb3). When in --replace mode we restrict overwrites to this set so
 * the hand-curated CTAs from `apply-save-this-tone.ts` are preserved.
 */
const PRIOR_BULK_SLUGS = new Set(
  fs
    .readFileSync(
      path.join(process.cwd(), "scripts", "save-this-tone-bulk-slugs.txt"),
      "utf-8",
    )
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean),
);

interface RecipeRef {
  recipeSlug: string;
  songTitle: string;
  artistName: string;
  artistSlug: string;
}

type Cta =
  | { kind: "recipe"; slug: string; reason: string }
  | {
      kind: "freeform";
      title: string;
      description: string;
      href: string;
      ctaLabel: string;
      reason: string;
    };

// Build artist → recipes index from the live catalog.
const artistToRecipes = new Map<string, RecipeRef[]>();
for (const r of toneRecipes) {
  const song = songs.find((s) => s.slug === r.song_slug);
  if (!song?.artist_slug) continue;
  const artist = artists.find((a) => a.slug === song.artist_slug);
  if (!artist) continue;
  const ref: RecipeRef = {
    recipeSlug: r.slug,
    songTitle: song.title,
    artistName: artist.name,
    artistSlug: song.artist_slug,
  };
  const list = artistToRecipes.get(song.artist_slug) ?? [];
  list.push(ref);
  artistToRecipes.set(song.artist_slug, list);
}

// Genre → list of song titles, for description copy.
const genreToSongs = new Map<string, RecipeRef[]>();
for (const r of toneRecipes) {
  const song = songs.find((s) => s.slug === r.song_slug);
  if (!song) continue;
  const artist = song.artist_slug
    ? artists.find((a) => a.slug === song.artist_slug)
    : undefined;
  const ref: RecipeRef = {
    recipeSlug: r.slug,
    songTitle: song.title,
    artistName: artist?.name ?? "",
    artistSlug: song.artist_slug ?? "",
  };
  for (const g of song.genres ?? []) {
    const list = genreToSongs.get(g) ?? [];
    list.push(ref);
    genreToSongs.set(g, list);
  }
}

// Platform tag → browse filter.
const PLATFORM_TAGS: Record<string, { slug: string; label: string }> = {
  helix: { slug: "helix", label: "Helix" },
  "line-6-helix": { slug: "helix", label: "Helix" },
  "hx-stomp": { slug: "helix", label: "HX Stomp" },
  katana: { slug: "katana", label: "Katana" },
  "boss-katana": { slug: "katana", label: "Katana" },
  tonex: { slug: "tonex", label: "TONEX" },
  "quad-cortex": { slug: "quad_cortex", label: "Quad Cortex" },
  fractal: { slug: "fractal", label: "Fractal" },
  kemper: { slug: "kemper", label: "Kemper" },
};

const TONE_TAGS: Record<string, { tag: string; label: string }> = {
  fuzz: { tag: "fuzz", label: "fuzz" },
  "big-muff": { tag: "fuzz", label: "fuzz" },
  "fuzz-face": { tag: "fuzz", label: "fuzz" },
  "high-gain": { tag: "high-gain", label: "high-gain" },
  djent: { tag: "high-gain", label: "high-gain" },
  metal: { tag: "high-gain", label: "high-gain" },
  clean: { tag: "clean", label: "clean" },
  ambient: { tag: "clean", label: "ambient clean" },
  jangly: { tag: "clean", label: "jangly clean" },
  shoegaze: { tag: "fuzz", label: "shoegaze" },
  worship: { tag: "clean", label: "worship-clean" },
  blues: { tag: "blues", label: "blues" },
  country: { tag: "clean", label: "country" },
  funk: { tag: "clean", label: "funk" },
};

const GENRE_TAGS = new Set([
  "blues",
  "metal",
  "rock",
  "punk",
  "grunge",
  "country",
  "shoegaze",
  "jazz",
  "funk",
  "indie",
  "classic-rock",
]);

// ── Copy templates ────────────────────────────────────────────────────────
// Phrasing rule: read it aloud — if it sounds like a press release, rewrite.
// Reference real songs/artists when the data supports it. Keep CTAs verbs.

function songList(refs: RecipeRef[], max = 3): string {
  const titles = refs.slice(0, max).map((r) => r.songTitle);
  if (titles.length === 1) return titles[0];
  if (titles.length === 2) return `${titles[0]} and ${titles[1]}`;
  return `${titles.slice(0, -1).join(", ")}, and ${titles[titles.length - 1]}`;
}

function artistList(refs: RecipeRef[], max = 4): string {
  const seen = new Set<string>();
  const names: string[] = [];
  for (const r of refs) {
    if (seen.has(r.artistName)) continue;
    seen.add(r.artistName);
    names.push(r.artistName);
    if (names.length >= max) break;
  }
  if (names.length === 1) return names[0];
  if (names.length === 2) return `${names[0]} and ${names[1]}`;
  return `${names.slice(0, -1).join(", ")}, and ${names[names.length - 1]}`;
}

interface Post {
  slug: string;
  filePath: string;
  raw: string;
  data: Record<string, unknown>;
  tags: string[];
}

function loadPosts(): Post[] {
  return fs
    .readdirSync(BLOG_DIR)
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => {
      const filePath = path.join(BLOG_DIR, f);
      const raw = fs.readFileSync(filePath, "utf-8");
      const fm = matter(raw);
      const tagsRaw = fm.data.tags;
      const tags: string[] = Array.isArray(tagsRaw)
        ? tagsRaw.map(String)
        : typeof tagsRaw === "string"
          ? [tagsRaw]
          : [];
      return {
        slug: f.replace(/\.mdx$/, ""),
        filePath,
        raw,
        data: fm.data as Record<string, unknown>,
        tags: tags.map((t) => t.toLowerCase()),
      };
    });
}

function classify(post: Post): Cta {
  // 1. Artist tag → first recipe (recipe-linked card; pulls live song/artist
  //    title and platform pills, way better than a generic browse link).
  for (const tag of post.tags) {
    const recipes = artistToRecipes.get(tag);
    if (!recipes || recipes.length === 0) continue;
    return {
      kind: "recipe",
      slug: recipes[0].recipeSlug,
      reason: `artist tag '${tag}' → ${recipes[0].recipeSlug}`,
    };
  }

  // 2. Platform tag.
  for (const tag of post.tags) {
    const p = PLATFORM_TAGS[tag];
    if (!p) continue;
    return {
      kind: "freeform",
      title: `Every recipe ships a ${p.label} preset`,
      description: `Block-by-block settings, the preset file, and a signal chain that actually translates. Load it and tweak from there.`,
      href: `/browse?platform=${p.slug}`,
      ctaLabel: `Browse ${p.label} recipes`,
      reason: `platform tag '${tag}'`,
    };
  }

  // 3. Tone-character.
  for (const tag of post.tags) {
    const t = TONE_TAGS[tag];
    if (!t) continue;
    return {
      kind: "freeform",
      title: `Want a ${t.label} starting point?`,
      description: `Pick a recipe close to the tone in this post and tweak from there. Faster than building from a blank patch.`,
      href: `/browse?tag=${t.tag}`,
      ctaLabel: `Browse ${t.label} recipes`,
      reason: `tone tag '${tag}'`,
    };
  }

  // 4. Genre.
  for (const tag of post.tags) {
    if (!GENRE_TAGS.has(tag)) continue;
    const refs = genreToSongs.get(tag) ?? [];
    const label = tag.replace(/-/g, " ");
    const description =
      refs.length > 0
        ? `${artistList(refs)} — settings, signal chain, presets to load.`
        : `Every recipe in the catalog has the chain, exact settings, and a preset to load.`;
    return {
      kind: "freeform",
      title: `${capFirst(label)} recipes in the catalog`,
      description,
      href: `/browse?genre=${encodeURIComponent(tag)}`,
      ctaLabel: `See the ${label} recipes`,
      reason: `genre tag '${tag}'`,
    };
  }

  // 5. Fallback.
  return {
    kind: "freeform",
    title: "Pick a tone to chase",
    description:
      "Every recipe in the catalog has the chain, exact settings, and a preset for Helix or Katana.",
    href: "/browse",
    ctaLabel: "Browse the catalog",
    reason: "fallback (no matching tag)",
  };
}

function capFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function buildCtaBlock(cta: Cta): string {
  if (cta.kind === "recipe") {
    return `\n\n<SaveThisTone recipeSlug="${cta.slug}" />\n`;
  }
  const escape = (s: string) => s.replace(/"/g, "&quot;");
  return `\n\n<SaveThisTone\n  title="${escape(cta.title)}"\n  description="${escape(cta.description)}"\n  href="${cta.href}"\n  ctaLabel="${escape(cta.ctaLabel)}"\n/>\n`;
}

/**
 * Strip a trailing `<SaveThisTone ... />` block from the file body.
 * Only matches blocks at the end of the file (whitespace-only after).
 * Returns the stripped body, or null if no match.
 */
function stripTrailingCta(raw: string): string | null {
  // Match either the multi-line freeform form OR the single-line recipe form.
  const multilineRe = /\n+<SaveThisTone\n[\s\S]*?\n\/>\s*$/;
  const inlineRe = /\n+<SaveThisTone\s+recipeSlug="[^"]+"\s*\/>\s*$/;

  if (multilineRe.test(raw)) return raw.replace(multilineRe, "");
  if (inlineRe.test(raw)) return raw.replace(inlineRe, "");
  return null;
}

function main() {
  const posts = loadPosts();

  let added = 0;
  let replaced = 0;
  let skipped = 0;
  let recipeKind = 0;
  let freeformKind = 0;

  const csvRows = ["slug,kind,target,reason"];

  for (const post of posts) {
    const hasCta = post.raw.includes("<SaveThisTone");

    if (hasCta && !REPLACE && !FORCE) {
      skipped++;
      continue;
    }

    // In --replace mode, restrict to the original bulk-backfill slugs so
    // hand-curated CTAs from apply-save-this-tone.ts stay untouched.
    if (hasCta && REPLACE && !FORCE && !PRIOR_BULK_SLUGS.has(post.slug)) {
      skipped++;
      continue;
    }

    let body = post.raw;
    if (hasCta && (REPLACE || FORCE)) {
      const stripped = stripTrailingCta(body);
      if (!stripped) {
        // CTA exists but isn't at the end (probably hand-placed mid-post).
        // Don't touch it.
        skipped++;
        continue;
      }
      body = stripped;
    }

    const cta = classify(post);
    const target = cta.kind === "recipe" ? `/recipe/${cta.slug}` : cta.href;
    csvRows.push(
      [post.slug, cta.kind, target, cta.reason.replace(/,/g, ";")].join(","),
    );
    if (cta.kind === "recipe") recipeKind++;
    else freeformKind++;

    if (APPLY) {
      const block = buildCtaBlock(cta);
      fs.writeFileSync(post.filePath, body.trimEnd() + block);
      if (hasCta) replaced++;
      else added++;
    } else {
      if (hasCta) replaced++;
      else added++;
    }
  }

  const csvOut = path.join(process.cwd(), "docs", "SAVE_THIS_TONE_BACKFILL.csv");
  fs.writeFileSync(csvOut, csvRows.join("\n") + "\n");

  console.log(`Posts processed: ${posts.length}`);
  console.log(`  → added (no prior CTA):    ${added}`);
  console.log(`  → replaced (had freeform): ${replaced}`);
  console.log(`  → skipped:                 ${skipped}`);
  console.log(`  → recipe-linked: ${recipeKind}`);
  console.log(`  → freeform:      ${freeformKind}`);
  console.log(`CSV: ${csvOut}`);
  console.log(
    APPLY
      ? "✓ Applied."
      : "Dry run. Re-run with --apply (and --replace to overwrite existing).",
  );
}

main();
