import type { PlatformTranslation } from "@/types/recipe";
import { resolveQCModel, categoryToQCType } from "./model-map";

/**
 * Parse a setting value to a numeric value suitable for QC presets.
 * QC uses raw parameter values (0-10 for knobs, 0-100 for mix, etc.)
 */
function parseParamValue(value: string | number | boolean): number {
  if (typeof value === "boolean") return value ? 1 : 0;
  if (typeof value === "number") return value;

  if (value.endsWith("%")) {
    return parseFloat(value) || 0;
  }
  if (value.toLowerCase() === "on" || value.toLowerCase() === "true") return 1;
  if (value.toLowerCase() === "off" || value.toLowerCase() === "false") return 0;

  const num = parseFloat(value);
  return isNaN(num) ? 5 : num;
}

/**
 * Build a single QC block object from a chain block.
 */
function buildQCBlock(
  blockName: string,
  category: string,
  settings: Record<string, string | number | boolean>,
  position: number,
  enabled: boolean,
): Record<string, unknown> {
  const modelName = resolveQCModel(blockName);
  const blockType = categoryToQCType(category);

  const params: Record<string, number> = {};
  for (const [key, value] of Object.entries(settings)) {
    params[key] = parseParamValue(value);
  }

  return {
    model: modelName,
    type: blockType,
    position,
    row: 0,
    enabled,
    params,
  };
}

/**
 * Generate a valid Quad Cortex .json preset string from a PlatformTranslation
 * and a preset name.
 *
 * The QC preset format is a JSON document with a specific structure that
 * can be imported via the Cortex desktop app or loaded from a USB drive.
 *
 * Blocks are placed sequentially in a single row (row 0).
 */
export function generateQCPreset(
  translation: PlatformTranslation,
  presetName: string,
): string {
  const blocks: Record<string, unknown>[] = [];

  for (let i = 0; i < translation.chain_blocks.length; i++) {
    const chainBlock = translation.chain_blocks[i];
    blocks.push(
      buildQCBlock(
        chainBlock.block_name,
        chainBlock.block_category,
        chainBlock.settings,
        i,
        true,
      ),
    );
  }

  const preset = {
    name: presetName.slice(0, 32),
    version: "2.0.0",
    schema: "QC_Preset",
    rows: 1,
    columns: blocks.length,
    scene: 0,
    bpm: 120,
    blocks,
    scenes: [
      {
        name: "Scene 1",
        active: true,
        blocks: blocks.map((_, i) => ({ index: i, enabled: true })),
      },
    ],
    controllers: {},
    meta: {
      created_by: "Fader & Knob",
      description: `${presetName} - generated by Fader & Knob`,
    },
  };

  return JSON.stringify(preset, null, 2);
}

/**
 * Slugify a preset name into a safe filename.
 */
export function slugifyPresetName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
